## Write a NumPy program to test element-wise for NaN of a given array.

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,5])
np.isnan(arr)

array([False, False, False, False])

In [3]:
arr=np.array([1,2,2.3,4])
np.isnan(arr)

array([False, False, False, False])

In [4]:
arr=np.array([1,2,0,4])
np.isnan(arr)

array([False, False, False, False])

In [5]:
arr = np.array([1, np.nan, 3, 4, np.nan, 6])    #np.nan -->not number
np.isnan(arr)

array([False,  True, False, False,  True, False])