## Import Library

In [2]:
import numpy as np

In [3]:
mylist=[3,5,7,10]  #list

In [4]:
print(mylist)

[3, 5, 7, 10]


In [5]:
myarray=np.array([3,5,7,11]) #array

In [6]:
print(myarray)

[ 3  5  7 11]


In [7]:
print(type(myarray))

<class 'numpy.ndarray'>


In [8]:
myarray.shape

(4,)

In [9]:
myarr=np.array([[3,5,7,11],[2,6,8,9],[1,2,3,4]])

In [10]:
myarr.shape

(3, 4)

In [11]:
my_arr=np.array([
    [[3,5,7,11],
     [2,6,8,9],
      [1,2,3,4]],
    [[20,30,40,50],
     [10,30,50,60],
     [60,70,80,90]]])

In [12]:
my_arr.shape

(2, 3, 4)

In [13]:
print(my_arr.size)

24


In [14]:
print(my_arr.ndim)

3


In [15]:
print(my_arr.dtype)

int32


## Access number in arrau

In [16]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
print(arr[0])

[1 2 3 4]


In [19]:
print(arr[0][0])

1


In [20]:
print(arr[1][0])

5


In [21]:
my_arr=np.array([
    [[3,5,7,11],
     [2,6,8,9],
      [1,2,3,4]],
    [[20,30,40,50],
     [10,30,50,60],
     [60,70,80,90]]])

In [22]:
print(my_arr[0][0][0])

3


In [23]:
print(my_arr[0,1,1])

6


## String Array

In [24]:
names=np.array(['gehad','ahmed','ali','mohamed'])

In [25]:
print(names)

['gehad' 'ahmed' 'ali' 'mohamed']


In [26]:
print(names.dtype)

<U7


In [27]:
name=np.array(['ali',5,True])

In [28]:
print(name)

['ali' '5' 'True']


In [29]:
print(name.dtype)

<U11


## Numbers of Array

In [30]:
numbers=np.array([1,2,3,4])

In [31]:
print(numbers)

[1 2 3 4]


In [32]:
print(numbers.dtype)

int32


In [33]:
numbers=np.array([1,2,3,'ali'])

In [34]:
print(numbers)

['1' '2' '3' 'ali']


In [35]:
print(type(numbers))

<class 'numpy.ndarray'>


In [36]:
numbers=np.array([1,2,3,'15'],dtype=np.int8)

In [37]:
print(numbers.dtype)

int8


In [38]:
c={'c':20}

In [39]:
numbers=np.array([1,2,3,'15',c])

In [40]:
print(numbers)

[1 2 3 '15' {'c': 20}]


## Full Array

In [41]:
full_arr=np.full((3,3,3),10)

In [42]:
print(full_arr)

[[[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]
  [10 10 10]]]


## Zero Array

In [43]:
zero_arr=np.zeros((3,3,3))

In [44]:
print(zero_arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Ones Array

In [45]:
ones_arr=np.ones((3,3,3))

In [46]:
print(ones_arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Mathematical operations

In [47]:
arr1=np.array([1,2,3,4])
arr2=np.array([5])

In [48]:
print(arr1+arr2)

[6 7 8 9]


In [49]:
print(arr1-arr2)

[-4 -3 -2 -1]


In [50]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,8,1])

In [51]:
print(arr1*arr2)

[ 5 12 24  4]


In [52]:
arr1=np.array([1,2,3,4])
arr2=np.array([[2],[3]])

In [53]:
print(arr1+arr2)

[[3 4 5 6]
 [4 5 6 7]]


In [54]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,8,1])

In [55]:
np.array_equal(arr1,arr2)

False

In [56]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])

In [57]:
np.array_equal  (arr1,arr2)

True

In [58]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[1,2,3,4],[5,6,7,8]])

In [59]:
np.array_equal(arr1,arr2)

True

In [60]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[1,2,3,4],[4,6,7,8]])

In [61]:
np.array_equal(arr1,arr2)

False

In [62]:
if np.array_equal(arr1,arr2):
    print('equal')
else:
    print('not equal')

not equal


## Append Array

In [63]:
a=np.array([1,2,3,4])

In [64]:
a2=np.append(a,[8,9])

In [65]:
print(a)
print(a2)

[1 2 3 4]
[1 2 3 4 8 9]


In [ ]:
a=np.array([1,2,3,4])
a2=np.insert(a,1,[8,9])        #in insert must detrmine index
print(a)
print(a2)

[1 2 3 4]
[1 8 9 2 3 4]


## Delete Element in Array

In [67]:
arr=np.array([1,2,3,4])
print(np.delete(arr,1))

[1 3 4]


In [68]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(np.delete(arr,0))

[2 3 4 5 6 7 8]


In [70]:
print(np.delete(arr,0,1))

[[2 3 4]
 [6 7 8]]


## Reshape Array

In [71]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [6,2,1,3,5]])
print(np.reshape(arr,(5,4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  6]
 [ 2  1  3  5]]


In [72]:
print(np.reshape(arr,(1,20)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  6  2  1  3  5]]


In [73]:
print(np.reshape(arr,(2,2,5)))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [ 6  2  1  3  5]]]


## Flatten Array
- convert any Dim Array to one dim array

In [74]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [6,2,1,3,5]])

print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  6  2  1  3  5]


## Transport Array
- Arrange the Array vertically

In [75]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [6,2,1,3,5]])

print(np.transpose(arr))

[[ 1  6 11  6]
 [ 2  7 12  2]
 [ 3  8 13  1]
 [ 4  9 14  3]
 [ 5 10 15  5]]


In [76]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [6,2,1,3,5]])

print(arr.T)

[[ 1  6 11  6]
 [ 2  7 12  2]
 [ 3  8 13  1]
 [ 4  9 14  3]
 [ 5 10 15  5]]


## Stack Array (Stack , vstack , hstack)
- merge more array

In [77]:
arr1=np.array([[1,2,3,4],[4,2,1,3]])
arr2=np.array([[5,6,7,8],[9,4,7,2]])
a=np.stack((arr1,arr2))
print(a)

[[[1 2 3 4]
  [4 2 1 3]]

 [[5 6 7 8]
  [9 4 7 2]]]


In [79]:
arr1=np.array([[1,2,3,4],[4,2,1,3]])
arr2=np.array([[5,6,7,8],[9,4,7,2]])
a=np.vstack((arr1,arr2))     #not space
print(a)

[[1 2 3 4]
 [4 2 1 3]
 [5 6 7 8]
 [9 4 7 2]]


In [80]:
arr1=np.array([[1,2,3,4],[4,2,1,3]])
arr2=np.array([[5,6,7,8],[9,4,7,2]])
a=np.hstack((arr1,arr2))
print(a)

[[1 2 3 4 5 6 7 8]
 [4 2 1 3 9 4 7 2]]


## Max Array
- return max value

In [81]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [6,2,1,3,5]])

print(arr.max())

15


In [82]:
print(arr.min())

1


In [83]:
print(arr.mean())

6.85


In [84]:
print(arr.sum())

137


In [85]:
print(np.median(arr))

6.0


## Random

In [86]:
number=np.random.randint(10)
print(number)

6


In [87]:
number=np.random.randint(10,20)
print(number)

13


In [88]:
number=np.random.randint(100,size=(5,4))
print(number)

[[68 28 47 87]
 [33 54 95 27]
 [54 12 94 17]
 [71  4 41 30]
 [64 75 56  7]]


In [89]:
number=np.random.randint(0,3,size=(5,4))
print(number)

[[1 2 1 2]
 [1 2 0 0]
 [2 0 2 1]
 [1 0 2 2]
 [1 0 1 2]]


In [90]:
number=np.array([1,3,6,8,14])
random_number=np.random.choice(number)
print(random_number)

3


## Save Array
- save array in file

In [91]:
arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [6,2,1,3,5]])

np.save('array.npy',arr)


In [92]:
a=np.load('array.npy')
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 6  2  1  3  5]]
