## Data Science Packages:
- pandas
- polars
- matplotlib
- plotly
- Dask
- Seaborn
- open cv
- mito
- pandas profiling

In [2]:
import math
print(math.pi)
# int x=4 --> 4byte c++
# x=4  -->16byte python

3.141592653589793


## Data types (numpy)
- int
- float
- complex
- bool 
- String 
- unicode 
- object

## int8 (8bit)
- 00000000   min
- 11111111   max
## int16 (16bit)
- 0000000000000000 min
- 1111111111111111 max
## int8 (sign may is - or +)
- 00000000  last bit 0 -->positive
- 10000000  last bit 1 -->negative
## uint8 (only positive +)
- 00000000 +

- (+one) 00000001  +1
- (-one) 10000001  -1
- *********************************************
- max number int8 --> -128 to 127
- max number unit8 --> 0 to 255

In [3]:
x=3.99999999999999999
x

4.0

In [4]:
1.1-0.9

0.20000000000000007

In [5]:
round(1.1-0.9,1)

0.2

## import numpy

In [6]:
import numpy as np 
#from numpy import * 
from numpy import mean,median

In [7]:
%whos

Variable   Type                        Data/Info
------------------------------------------------
math       module                      <module 'math' (built-in)>
mean       _ArrayFunctionDispatcher    <function mean at 0x0000024C3CAC0180>
median     _ArrayFunctionDispatcher    <function median at 0x0000024C3CBEF1A0>
np         module                      <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
x          float                       4.0


In [8]:
myarr=np.array([1])
type(myarr)

numpy.ndarray

In [9]:
myarr=np.array([1,2,4])  
type(myarr)

numpy.ndarray

In [10]:
myarr.dtype

dtype('int32')

In [11]:
myarr=np.array([1,2,4],dtype='f4')   #float 4byte
myarr

array([1., 2., 4.], dtype=float32)

In [12]:
myarr=np.array([1,2,4],dtype='float32')   #float 4byte
myarr

array([1., 2., 4.], dtype=float32)

In [13]:
myarr=np.array([1,2,4])   #int32-->each number is 4byte
myarr.dtype, myarr.nbytes  #-> 3*4byte

(dtype('int32'), 12)

In [14]:
myarr=np.array([1,2,4],dtype='int8')   #int8-->each number is 1byte
myarr.dtype, myarr.nbytes           #-->3*1byte

(dtype('int8'), 3)

In [15]:
arr=np.array([1,2,'ahmed'],dtype='float32')
arr.dtype

for i in arr:
  print(i)            #error beacuse cannot convert ahmed for flot

ValueError: could not convert string to float: 'ahmed'

In [ ]:
arr=np.array([1,2,'3.4'],dtype='float32')
arr.dtype

for i in arr:
  print(i) 

1.0
2.0
3.4


In [ ]:
arr=np.array(['1','2','3'],dtype='int')
arr.dtype

for i in arr:
  print(i) 

1
2
3


In [ ]:
arr=np.array([1,2,'3'],dtype='float32')
arr.dtype

for i in arr:
  print(i) 

1.0
2.0
3.0


## astype (convert data type)

In [ ]:
arr=np.array([1,2,3],dtype='int16')  #16/8--->2byte
print('Orginal Data Types : '+str(arr.dtype))
print(arr.nbytes)
arr=arr.astype('float32')  #convert type 
print('After Conversion Data Types : '+str(arr.dtype))
print(arr.nbytes)

Orginal Data Types : int16
6
After Conversion Data Types : float32
12


In [ ]:
arr=np.array([126,127,128],dtype='int16')  #16/8--->2byte
print('Orginal Data Types : '+str(arr.dtype))
print('Data : '+str(arr))
print(arr.nbytes)
arr=arr.astype('int8')  #overflow
print('After Conversion Data Types : '+str(arr.dtype))
print('Data : '+str(arr))
print(arr.nbytes)

Orginal Data Types : int16
Data : [126 127 128]
6
After Conversion Data Types : int8
Data : [ 126  127 -128]
3


In [ ]:
arr.max()

127

In [ ]:
max(arr)

127

In [ ]:
s=np.array(['ahmed','ali'],dtype='S3')
print(s)
s=np.array(['minium','maxmum'],dtype='U3')
print(s)

[b'ahm' b'ali']
['min' 'max']


In [ ]:
arr=np.array(['a','ab','abc','abcd'],dtype=np.string_)
print(arr.dtype)
print(max(arr))
arr=np.array(['a','ab','abc','abcdsw'],dtype=np.unicode_)
print(arr.dtype)
print(max(arr))

|S4
b'abcd'
<U6
abcdsw


## Create an array from on iterable
- list
- tuple
- range
- iterator

In [ ]:
mylist=[1,2,3,4]
myarr=np.array(mylist)
print(myarr)
print(myarr.dtype)
print('*'*7)
l=[1,2,3,4]
print(l)


[1 2 3 4]
int32
*******
[1, 2, 3, 4]


In [ ]:
arr=np.array((1,2,3,4))      #tuple
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [ ]:
arr=np.array(range(10,21,2))
print(arr)
print(arr.dtype)
arr=arr.astype('int8')
print(arr.dtype)

[10 12 14 16 18 20]
int32
int8


In [ ]:
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
identity_matrix=np.eye(5).astype('int8')
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
identity_matrix=np.identity(3).astype('int8')
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
print(arr.itemsize)   #each element in array how many size(bytes)

1


In [ ]:
# memory size of an array(bytes)
print(arr.nbytes)
print((arr.nbytes)*8)  #bits

6
48


## Random Numbers

In [ ]:
np.random.rand(2)

array([0.23163051, 0.78098631])

In [ ]:
np.random.seed(11)   #seed -->fixed random numbers and must take number
np.random.rand(4)

array([0.18026969, 0.01947524, 0.46321853, 0.72493393])

In [16]:
np.random.choice([1,2,3,4,5],2)

array([2, 3])

In [17]:
np.random.choice(['gehad','ahmed','ali','mohamed'],2)

array(['gehad', 'mohamed'], dtype='<U7')

## Generate 3-D array

In [18]:
print(np.random.rand(3,3,3))

[[[0.48363597 0.49328229 0.66512354]
  [0.24459227 0.18962125 0.28135325]
  [0.91398942 0.50444962 0.41849487]]

 [[0.87791381 0.64499526 0.36079757]
  [0.389392   0.20430682 0.32951132]
  [0.87754998 0.70322833 0.75192004]]

 [[0.11410385 0.39332184 0.43010934]
  [0.9299141  0.38292545 0.22170075]
  [0.23713274 0.14426823 0.64391512]]]


In [19]:
np.random.randint(1,10,3,dtype='i8')

array([8, 3, 4], dtype=int64)

In [20]:
def generate_random(start,end,n):
  return np.random.randint(start,end,n)

In [21]:
generate_random(1,10,3)

array([2, 1, 5])

In [22]:
np.random.choice(range(3),10,replace=True,p=[0.1,0.3,0.6])

array([1, 2, 2, 1, 2, 2, 2, 2, 2, 1])

## Shuffle an array in place

In [23]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [24]:
np.random.shuffle(arr)
print(arr)

[2 1 5 4 3]


## generate a permutation of an array

In [25]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [26]:
np.random.permutation(arr)

array([2, 4, 3, 1, 5])

In [27]:
np.random.rand(5,5)

array([[0.58429944, 0.3013002 , 0.3076652 , 0.00182533, 0.21420445],
       [0.9381364 , 0.58854836, 0.34009745, 0.27016512, 0.05329567],
       [0.54035894, 0.16078306, 0.14539865, 0.7286361 , 0.76817426],
       [0.98232436, 0.64612665, 0.04289014, 0.66609115, 0.32362612],
       [0.62688992, 0.92585443, 0.34101158, 0.92440939, 0.75813618]])

## Adittion,substraction,.....array

In [28]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[11 12 13 14 15]
[-9 -8 -7 -6 -5]
[10 20 30 40 50]
[0.1 0.2 0.3 0.4 0.5]


In [29]:
arr1=np.array([1,2,3])
x=np.add(arr1,[5,6,7],out=arr1)
print(x)
y=np.subtract(arr1,[8,9,7],out=arr1)
print(y)
z=np.multiply(arr1,[1,2,3],out=arr1)
print(z)

[ 6  8 10]
[-2 -1  3]
[-2 -2  9]


## element wise exponention

In [31]:
np.exp(arr1)   #e اس --->number

array([1.35335283e-01, 1.35335283e-01, 8.10308393e+03])

## element wise logorithm

In [ ]:
np.log(arr)        #log base e

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
np.log2(arr)      ##log base e

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

## element wise square root

In [34]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

## element wise sin and cosine

In [35]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [37]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

## sum along specified axis

In [ ]:
arra=np.array([[1,2,3],[4,5,6]])       #2*3
np.sum(arra,axis=0)      #sum each row

array([5, 7, 9])

In [39]:
arra=np.array([[1,2,3],[4,5,6]])
np.sum(arra,axis=1)        #sum each column

array([ 6, 15])

In [ ]:
np.argmin([1,2,5,7,0])       #index -->smallest number

4

In [41]:
np.argmax([1,2,5,7,0])

3

In [43]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.maximum(arr1,arr2))
print(np.minimum(arr1,arr2))

[4 5 6]
[1 2 3]


## compute the mean

In [44]:
np.mean(arr1)

2.0

In [48]:
np.mean(arr1,axis=0)        #mean row

2.0

## compute the median

In [49]:
x=[1,2,3,4,5,6,7]
np.median(x)

4.0

In [50]:
np.median(arr1,axis=0)

2.0

## compute standerd deviation and variance

In [51]:
np.std(arr1)

0.816496580927726

In [52]:
np.var(arr1)

0.6666666666666666

In [53]:
arr_range=np.array(range(100))
arr_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr_range.shape             #100 value in one row

(100,)

In [65]:
arr=arr_range.reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
arr_range.reshape(50,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [67]:
arr[5][5]

55

In [68]:
arr[5,5]

55

## indexing with slicing

In [ ]:
arr[1:3 :]     #from 1 to 3 (all columns)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## sort array

In [70]:
np.sort(arr,axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## transpose array

In [72]:
arr.transpose()

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [73]:
arr.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

## faltten array (1 Dim)

In [74]:
new=arr.flatten()
new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [75]:
new.shape

(100,)

In [76]:
new.ndim

1

## apaned elment to an array

In [77]:
arr=np.array([1,2,3])
arr1=np.append(arr,4)
arr1

array([1, 2, 3, 4])

In [78]:
arr3=np.insert(arr,2,5)
arr3

array([1, 2, 5, 3])

In [ ]:
arr4=np.delete(arr,1) #1 -->index
arr4

array([1, 3])

In [80]:
arr5=np.delete(arr,[0,2]) #0 and 2 -->index
arr5

array([2])

## copy an array

In [81]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [83]:
arrx=arr
arrx[0]=7
arrx

array([7, 2, 3])

In [84]:
arr

array([7, 2, 3])

In [85]:
np.info(arr)

class:  ndarray
shape:  (3,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x24c3b760270
byteorder:  little
byteswap:  False
type: int32


In [ ]:
np.info(arrx)   #arrx==arr (same pointer)

class:  ndarray
shape:  (3,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x24c3b760270
byteorder:  little
byteswap:  False
type: int32


In [87]:
arr1=np.copy(arr)
arr1
#or
a=arr.copy()
a
#or
arr1=np.array(arr,copy=True)
arr1

array([7, 2, 3])

## Concatination

In [88]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
arr3=np.concatenate((arr1,arr2),axis=0)
arr3

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [89]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
arr3=np.concatenate((arr1,arr2),axis=1)
arr3

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
cat=np.vstack((arr1,arr2))   #vstack-->vertical
cat

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [93]:
cat=np.r_[arr1,arr2]
cat 

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [91]:
cat=np.hstack((arr1,arr2))
cat

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
cat=np.c_[arr1,arr2]
cat

## split an array

In [94]:
arr=np.random.rand(6,6)
arr

array([[0.12807712, 0.80601046, 0.47548981, 0.79501909, 0.39283509,
        0.09132946],
       [0.21036573, 0.11332407, 0.67286763, 0.8914029 , 0.59063579,
        0.68743314],
       [0.65462466, 0.13785533, 0.03890538, 0.19660483, 0.02308472,
        0.44731947],
       [0.54775839, 0.88166093, 0.22179183, 0.45295934, 0.44719736,
        0.94719637],
       [0.19888404, 0.15751813, 0.01153161, 0.98468619, 0.47400827,
        0.95757341],
       [0.83249707, 0.13144871, 0.62496816, 0.07071046, 0.35862859,
        0.86311764]])

In [95]:
arr1=np.vsplit(arr,2)
arr1

[array([[0.12807712, 0.80601046, 0.47548981, 0.79501909, 0.39283509,
         0.09132946],
        [0.21036573, 0.11332407, 0.67286763, 0.8914029 , 0.59063579,
         0.68743314],
        [0.65462466, 0.13785533, 0.03890538, 0.19660483, 0.02308472,
         0.44731947]]),
 array([[0.54775839, 0.88166093, 0.22179183, 0.45295934, 0.44719736,
         0.94719637],
        [0.19888404, 0.15751813, 0.01153161, 0.98468619, 0.47400827,
         0.95757341],
        [0.83249707, 0.13144871, 0.62496816, 0.07071046, 0.35862859,
         0.86311764]])]

In [96]:
arr2=np.hsplit(arr,2)
arr2

[array([[0.12807712, 0.80601046, 0.47548981],
        [0.21036573, 0.11332407, 0.67286763],
        [0.65462466, 0.13785533, 0.03890538],
        [0.54775839, 0.88166093, 0.22179183],
        [0.19888404, 0.15751813, 0.01153161],
        [0.83249707, 0.13144871, 0.62496816]]),
 array([[0.79501909, 0.39283509, 0.09132946],
        [0.8914029 , 0.59063579, 0.68743314],
        [0.19660483, 0.02308472, 0.44731947],
        [0.45295934, 0.44719736, 0.94719637],
        [0.98468619, 0.47400827, 0.95757341],
        [0.07071046, 0.35862859, 0.86311764]])]

## unique

In [97]:
arr=np.array([1,2,8,8,3,9,9,9])
np.unique(arr)

array([1, 2, 3, 8, 9])

In [98]:
arr=np.array([1,2,8,8,3,9,9,9])
unque,counts=np.unique(arr,return_counts=True)
print(unque)
print(counts)

[1 2 3 8 9]
[1 1 1 2 3]


## compute the intersaction and union

In [101]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,2,7,4])
np.intersect1d(arr1,arr2)
print(np.intersect1d(arr1,arr2))
type(np.intersect1d(arr1,arr2))

[2 4]


numpy.ndarray

In [ ]:
print(np.union1d(arr1,arr2))     #union -->not duplicate

[1 2 3 4 5 7]


## where (take element and return index)

In [106]:
arr1=np.array([1,2,3,4,3])
np.where(arr1==2)

(array([1], dtype=int64),)

In [107]:
np.where(arr1==3)

(array([2, 4], dtype=int64),)

In [108]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,2,7,4])
print(np.in1d(arr1,arr2))

[False  True False  True]


In [109]:
print(np.setdiff1d(arr1,arr2))

[1 3]


In [110]:
print(np.setdiff1d(arr2,arr1))

[5 7]


In [111]:
print(np.setxor1d(arr1,arr2))

[1 3 5 7]


## save file numpy

In [117]:
a=np.array([1,2,3,4])
np.savetxt('arr.txt',a,fmt='%d')


In [ ]:
b=np.loadtxt('array.txt',dtype='int')
b

array([1, 2, 3, 4])

In [121]:
a.tofile('array3.dat')
b=np.fromfile('array3.dat',dtype='int')
b

array([1, 2, 3, 4])

In [122]:
np.save('array.npy',a)
b=np.load('array.npy')
b

array([1, 2, 3, 4])