## Data Science Packages:
- pandas
- polars
- matplotlib
- plotly
- Dask
- Seaborn
- open cv
- mito
- pandas profiling

In [2]:
import math
print(math.pi)
# int x=4 --> 4byte c++
# x=4  -->16byte python

3.141592653589793


## Data types (numpy)
- int
- float
- complex
- bool 
- String 
- unicode 
- object

## int8 (8bit)
- 00000000   min
- 11111111   max
## int16 (16bit)
- 0000000000000000 min
- 1111111111111111 max
## int8 (sign may is - or +)
- 00000000  last bit 0 -->positive
- 10000000  last bit 1 -->negative
## uint8 (only positive +)
- 00000000 +

- (+one) 00000001  +1
- (-one) 10000001  -1
- *********************************************
- max number int8 --> -128 to 127
- max number unit8 --> 0 to 255

In [3]:
x=3.99999999999999999
x

4.0

In [4]:
1.1-0.9

0.20000000000000007

In [5]:
round(1.1-0.9,1)

0.2

## import numpy

In [6]:
import numpy as np 
#from numpy import * 
from numpy import mean,median

In [7]:
%whos

Variable   Type                        Data/Info
------------------------------------------------
math       module                      <module 'math' (built-in)>
mean       _ArrayFunctionDispatcher    <function mean at 0x0000024C3CAC0180>
median     _ArrayFunctionDispatcher    <function median at 0x0000024C3CBEF1A0>
np         module                      <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
x          float                       4.0


In [8]:
myarr=np.array([1])
type(myarr)

numpy.ndarray

In [9]:
myarr=np.array([1,2,4])  
type(myarr)

numpy.ndarray

In [10]:
myarr.dtype

dtype('int32')

In [11]:
myarr=np.array([1,2,4],dtype='f4')   #float 4byte
myarr

array([1., 2., 4.], dtype=float32)

In [12]:
myarr=np.array([1,2,4],dtype='float32')   #float 4byte
myarr

array([1., 2., 4.], dtype=float32)

In [13]:
myarr=np.array([1,2,4])   #int32-->each number is 4byte
myarr.dtype, myarr.nbytes  #-> 3*4byte

(dtype('int32'), 12)

In [14]:
myarr=np.array([1,2,4],dtype='int8')   #int8-->each number is 1byte
myarr.dtype, myarr.nbytes           #-->3*1byte

(dtype('int8'), 3)

In [15]:
arr=np.array([1,2,'ahmed'],dtype='float32')
arr.dtype

for i in arr:
  print(i)            #error beacuse cannot convert ahmed for flot

ValueError: could not convert string to float: 'ahmed'

In [ ]:
arr=np.array([1,2,'3.4'],dtype='float32')
arr.dtype

for i in arr:
  print(i) 

1.0
2.0
3.4


In [ ]:
arr=np.array(['1','2','3'],dtype='int')
arr.dtype

for i in arr:
  print(i) 

1
2
3


In [ ]:
arr=np.array([1,2,'3'],dtype='float32')
arr.dtype

for i in arr:
  print(i) 

1.0
2.0
3.0


## astype (convert data type)

In [ ]:
arr=np.array([1,2,3],dtype='int16')  #16/8--->2byte
print('Orginal Data Types : '+str(arr.dtype))
print(arr.nbytes)
arr=arr.astype('float32')  #convert type 
print('After Conversion Data Types : '+str(arr.dtype))
print(arr.nbytes)

Orginal Data Types : int16
6
After Conversion Data Types : float32
12


In [ ]:
arr=np.array([126,127,128],dtype='int16')  #16/8--->2byte
print('Orginal Data Types : '+str(arr.dtype))
print('Data : '+str(arr))
print(arr.nbytes)
arr=arr.astype('int8')  #overflow
print('After Conversion Data Types : '+str(arr.dtype))
print('Data : '+str(arr))
print(arr.nbytes)

Orginal Data Types : int16
Data : [126 127 128]
6
After Conversion Data Types : int8
Data : [ 126  127 -128]
3


In [ ]:
arr.max()

127

In [ ]:
max(arr)

127

In [ ]:
s=np.array(['ahmed','ali'],dtype='S3')
print(s)
s=np.array(['minium','maxmum'],dtype='U3')
print(s)

[b'ahm' b'ali']
['min' 'max']


In [ ]:
arr=np.array(['a','ab','abc','abcd'],dtype=np.string_)
print(arr.dtype)
print(max(arr))
arr=np.array(['a','ab','abc','abcdsw'],dtype=np.unicode_)
print(arr.dtype)
print(max(arr))

|S4
b'abcd'
<U6
abcdsw


## Create an array from on iterable
- list
- tuple
- range
- iterator

In [ ]:
mylist=[1,2,3,4]
myarr=np.array(mylist)
print(myarr)
print(myarr.dtype)
print('*'*7)
l=[1,2,3,4]
print(l)


[1 2 3 4]
int32
*******
[1, 2, 3, 4]


In [ ]:
arr=np.array((1,2,3,4))      #tuple
print(arr)
print(type(arr))
print(arr.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [ ]:
arr=np.array(range(10,21,2))
print(arr)
print(arr.dtype)
arr=arr.astype('int8')
print(arr.dtype)

[10 12 14 16 18 20]
int32
int8


In [ ]:
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
identity_matrix=np.eye(5).astype('int8')
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
identity_matrix=np.identity(3).astype('int8')
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
print(arr.itemsize)   #each element in array how many size(bytes)

1


In [ ]:
# memory size of an array(bytes)
print(arr.nbytes)
print((arr.nbytes)*8)  #bits

6
48


## Random Numbers

In [ ]:
np.random.rand(2)

array([0.23163051, 0.78098631])

In [ ]:
np.random.seed(11)   #seed -->fixed random numbers and must take number
np.random.rand(4)

array([0.18026969, 0.01947524, 0.46321853, 0.72493393])

In [16]:
np.random.choice([1,2,3,4,5],2)

array([2, 3])

In [17]:
np.random.choice(['gehad','ahmed','ali','mohamed'],2)

array(['gehad', 'mohamed'], dtype='<U7')

## Generate 3-D array

In [18]:
print(np.random.rand(3,3,3))

[[[0.48363597 0.49328229 0.66512354]
  [0.24459227 0.18962125 0.28135325]
  [0.91398942 0.50444962 0.41849487]]

 [[0.87791381 0.64499526 0.36079757]
  [0.389392   0.20430682 0.32951132]
  [0.87754998 0.70322833 0.75192004]]

 [[0.11410385 0.39332184 0.43010934]
  [0.9299141  0.38292545 0.22170075]
  [0.23713274 0.14426823 0.64391512]]]


In [19]:
np.random.randint(1,10,3,dtype='i8')

array([8, 3, 4], dtype=int64)

In [20]:
def generate_random(start,end,n):
  return np.random.randint(start,end,n)

In [21]:
generate_random(1,10,3)

array([2, 1, 5])

In [22]:
np.random.choice(range(3),10,replace=True,p=[0.1,0.3,0.6])

array([1, 2, 2, 1, 2, 2, 2, 2, 2, 1])